alibaba/pipcook

- README.md
> docs: UPDATE README.md, trivial changes

- README.md
As the title of this pull request, fixes some typos and inconsistent markdown rules :)
> readme: fix some typos and syntaxs

- packages/pipcook-core/src/board/board.ts
- packages/pipcook-core/src/components/PipcookLifeCycleComponent.ts
- packages/pipcook-core/src/core/core.ts
- packages/pipcook-core/src/types/component.ts
- packages/pipcook-core/src/types/data.ts
- packages/pipcook-core/src/types/model.ts
- packages/pipcook-core/src/types/other.ts
- packages/pipcook-core/src/types/plugins.ts
- packages/pipcook-plugins-bayesian-classifier-model-train/src/index.ts
- packages/pipcook-plugins-detection-detectron-data-access/src/index.ts
- packages/pipcook-plugins-detection-detectron-model-evaluate/src/index.ts
- packages/pipcook-plugins-image-class-data-access/src/index.ts
- packages/pipcook-plugins-image-coco-data-collect/src/index.ts
- packages/pipcook-plugins-image-detection-data-access/src/index.ts
- packages/pipcook-plugins-image-mnist-data-collect/src/index.ts
- packages/pipcook-plugins-local-mobileNet-model-load/src/index.ts
- packages/pipcook-plugins-model-evaluate/src/index.ts
- packages/pipcook-plugins-simple-cnn-model-load/src/index.ts
- packages/pipcook-plugins-text-class-data-collect/src/index.ts
- packages/pipcook-plugins-text-class-local-model-deploy/src/index.ts
- packages/pipcook-plugins-text-csv-data-access/src/index.ts
- packages/pipcook-python-node/src/communication/communication.ts
- packages/pipcook-python-node/src/core/python-helper.ts
- packages/pipcook-python-node/src/core/python.ts
- packages/pipcook-python-node/src/types/python-object.ts
The changes include many files, @utkobe may I ask you to help me to review this and be careful :)
> build: fix some lint errors by eslint --fix

- .eslintrc.js
- packages/pipcook-plugins-detection-detectron-data-access/src/index.ts
- packages/pipcook-plugins-detection-detectron-eas-model-deploy/src/index.ts
- packages/pipcook-plugins-detection-detectron-model-load/src/index.ts
- packages/pipcook-plugins-image-class-data-process/src/index.ts
- packages/pipcook-plugins-image-class-eas-deploy/src/index.ts
- packages/pipcook-plugins-image-class-local-model-deploy/src/index.ts
- packages/pipcook-plugins-image-mnist-data-collect/src/index.ts
- packages/pipcook-plugins-local-mobileNet-model-load/src/index.ts
- packages/pipcook-plugins-model-evaluate/src/index.ts
- packages/pipcook-plugins-model-train/src/index.ts
- packages/pipcook-plugins-simple-cnn-model-load/src/index.ts
- packages/pipcook-plugins-text-class-data-process/src/index.ts
- packages/pipcook-plugins-text-class-local-model-deploy/src/index.ts
All errors have been fixed in this pull request, and we can build CI after this gets merged :)
> build: fix lint errors in plugins

- .github/workflows/build.yml
- package.json
- packages/pipcook-core/src/core/core-helper.ts
- packages/pipcook-plugins-bayesian-classifier-model-train/src/index.ts
- packages/pipcook-plugins-image-class-data-process/src/index.ts
It enables GitHub Actions for Pipcook, removing the old configs for travis/appveyor until the GitHub Actions build is stable.
@utkobe Please review and merge this util the CI is green, thank you :)
> build: add github actions config and tweak npm scripts

- README.md
Add the GitHub Action badge on the readme :)
> readme: add github action badge

- docs/meta/PROJECT_GUIDE.md
This adds the related documentations by #17 and #15.
> meta: add meta docs

- .github/workflows/gh-pages.yml
Forgot to remove this trigger branch at #39.
> meta: remove unneeded trigger for gh-pages

- README.md
As discussed with @shadowkun , just add a download link for users, both in English and Chinese. Please have a review please @yorkie
> add download link for dingtalk

- docs/_sidebar.md
- docs/zh-cn/_sidebar.md
We should removed the sidebar links after #62.
> doc: remove the links that not exists at siderbar

- .github/workflows/pipeline.yml
- .gitignore
- package-lock.json
- package.json
- packages/boa/package-lock.json
- packages/cli/lib/runConfig.js
- packages/cli/lib/start.js
- packages/core/src/runner/index.ts
- packages/plugins/model-define/tfjs-mobilenet-model-define/src/index.ts
- run_pipeline.sh
- test/pipelines/databinding-image-classification.json
- test/pipelines/mnist-image-classification.json
This is to close #82, then it helps us to check if the pipeline and related models are working.
> build: run/test pipelines at github actions

- .github/workflows/pipeline.yml
- run_pipeline.sh
Add 'mnist-image-classification' and 'databinding-image-classification' in our Pipeline CI.
> build: add more pipelines

- docs/README.md
> docs: fix typos.

- packages/plugins/model-define/bayesian-model-define/package.json
> plugin: remove unnecessary file and dir.

- packages/cli/lib/start.js
Could I add unit test for cli in /packages/cli/test, and use 'mocha' as tool.
> cli: checking config file exist or not.

- README.md
- docs/tutorials/get-started-with-cli.md
- docs/zh-cn/tutorials/get-started-with-cli.md
- package-lock.json
- packages/boa/tools/install-python.js
- packages/cli/bin/index.js
- packages/cli/lib/init.js
Added `--tuna` for using the awesome Python mirror(https://mirror.tuna.tsinghua.edu.cn/help/pypi/) to speed up the `init` command.
> cli: use tuna for less init cost

- README.md
- docs/README.md
- docs/tutorials/want-to-use-python.md
- docs/zh-cn/README.md
- docs/zh-cn/tutorials/want-to-use-python.md
Update the documents to show how to predict using trained model. Also add instructions on how to install packages using bip.
> update document to include serving infomation

- docs/devel/developer-guide.md
- docs/zh-cn/devel/developer-guide.md
Add our basic usage for our contributors.
/cc @wordcount @utkobe
> docs: add contribution documentation

- packages/boa/lib/index.js
- packages/boa/tests/base/basic.js
- packages/boa/tests/numpy/ndarray.js
- packages/boa/tests/numpy/routines.matrix.js
> boa: support toJSON on proxy object

- packages/core/src/runner/helper.ts
- packages/core/src/types/component.ts
- packages/core/src/types/config.ts
- packages/core/src/types/data/common.ts
- packages/core/src/types/data/image.ts
- packages/pipboard-server/app/utils/types.ts
- packages/plugins/data-access/coco-data-access/src/index.ts
- packages/plugins/data-access/csv-data-access/src/index.ts
- packages/plugins/data-access/pascalvoc-data-access/src/index.ts
- packages/plugins/data-collect/image-classification-data-collect/src/index.ts
Hi, I am first to contribute to open source, if there any issues, please despite telling me
Closes #142
> refactor(type): use Record instead of custom object

- .github/workflows/cli.yml
- packages/cli/src/commands/board.ts
- packages/cli/src/commands/dataset.ts
- packages/cli/src/commands/devPlugin.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/serve.ts
- packages/cli/src/commands/start.ts
> cli: exit with code when failed.

- .github/workflows/cli.yml
- packages/cli/src/commands/devPlugin.ts
> cli: fix cli workflow err.

- example/boa/sklearn/gradient-boosting-regression.js
Add sklearn gradient boosting regression example, see https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_regression.html?highlight=feature_importance
> examples: add gradient-boosting-regression

- packages/core/src/components/lifecycle.ts
- packages/core/src/runner/helper.ts
- packages/core/src/runner/index.ts
- packages/core/src/types/component.ts
- packages/core/src/types/plugins.ts
This PR improves the type of pipcook's runner as possible, and there still have some work TBD for `utils` or `types`
> core: add typings for runner

- packages/boa/esm/loader.mjs
With simple `py:` protocol to transfer between hook.
> boa: Modify the Python path protocol to py:

- packages/plugins/model-train/image-classification-tfjs-model-train/src/index.ts
Just change the `Number` constructor to `Math.floor`.
> plugin: math.floor instead of Number constructor

- packages/costa/src/index.ts
- packages/costa/src/runtime.ts
- packages/plugins/data-collect/csv-data-collect/src/index.ts
- packages/plugins/model-define/tensorflow-resnet-model-define/src/index.ts
- packages/plugins/model-define/tfjs-mobilenet-model-define/src/index.ts
- packages/plugins/model-load/tensorflow-model-load/src/index.ts
> fix typo error

- .github/workflows/cli.yml
- packages/daemon/src/app/controller/pipeline.ts
- packages/plugins/model-define/bayesian-model-define/package.json
- packages/plugins/model-define/fasttext-model-define/package.json
- packages/plugins/model-evaluate/fasttext-model-evaluate/package.json
- packages/plugins/model-train/fasttext-model-train/package.json
`boa` was upgraded to 0.6.0,  the dependence of plugins needs to be upgraded too.
> plugins: fix boa version

- example/pipelines/databinding-image-classification.json
- package-lock.json
- packages/boa/package-lock.json
- packages/cli/package-lock.json
- packages/costa/package-lock.json
- packages/costa/src/runtime.ts
- packages/pipboard/package-lock.json
- packages/plugins/model-evaluate/image-classification-tensorflow-model-evaluate/package-lock.json
- packages/plugins/model-evaluate/image-classification-tensorflow-model-evaluate/package.json
- packages/plugins/model-train/image-classification-tensorflow-model-train/package-lock.json
- packages/plugins/model-train/image-classification-tensorflow-model-train/package.json
1. add a default timeout to pip install. Otherwise, it failed frequently
2. remove file in package.json
> add default timeout for pip install

- .eslintrc.js
- packages/cli/src/actions/dev-plugin.ts
- packages/core/src/index.ts
- packages/core/src/types/component.ts
- packages/core/src/types/data/image.ts
- packages/core/src/types/plugins.ts
- packages/core/src/utils/public.ts
- packages/costa/src/client.ts
- packages/costa/src/index.ts
- packages/costa/src/runnable.ts
- packages/costa/src/runtime.ts
- packages/plugins/data-access/coco-data-access/src/index.ts
- packages/plugins/data-access/csv-data-access/src/index.ts
- packages/plugins/data-access/pascalvoc-data-access/src/index.ts
- packages/plugins/model-define/bayesian-model-define/src/index.ts
- packages/plugins/model-define/detectron-fasterrcnn-model-define/src/index.ts
- packages/plugins/model-define/detectron-maskrcnn-model-define/src/index.ts
- packages/plugins/model-define/fasttext-model-define/src/index.ts
- packages/plugins/model-define/tensorflow-resnet-model-define/src/index.ts
- packages/plugins/model-define/tfjs-mobilenet-model-define/src/index.ts
- packages/plugins/model-define/tfjs-simplecnn-model-define/src/index.ts
- packages/plugins/model-evaluate/bayesian-model-evaluate/src/index.ts
- packages/plugins/model-evaluate/bayesian-model-evaluate/src/script.ts
- packages/plugins/model-evaluate/image-classification-tfjs-model-evaluate/src/index.ts
- packages/plugins/model-train/bayesian-model-train/src/index.ts
- packages/plugins/model-train/bayesian-model-train/src/script.ts
> eslint: add rule no-trailing-spaces

- packages/boa/lib/index.js
- packages/boa/tools/install-python.js
- packages/boa/tools/utils.js
In this PR, we use the specific Python binary for interrupting the Pip and Conda script to avoid environment issues.
> boa: fix the install script python

- packages/plugins/model-define/tfjs-mobilenet-model-define/src/index.ts
Update hiddenLayerUnits arg of tfjs mobilenet plugin
> doc: update tfjs mobilenet args

- test/pipelines/image-generation-cycle-gan.json
> fix: update plugin name in cycle gan pipeline

- packages/cli/src/actions/init.ts
- packages/cli/src/bin/pipcook.ts
- packages/cli/src/utils.ts
- packages/core/src/constants/other.ts
- packages/core/src/index.ts
- packages/daemon/src/boot/database.ts
- packages/daemon/src/boot/plugin.ts
- packages/daemon/src/service/app.ts
- packages/daemon/src/service/pipeline.ts
Moved some constants into core's constants, and improved the `pipcook --version` outputs all versions.
> core: move some constants into core

- packages/daemon/src/service/pipeline.ts
- packages/plugins/model-define/detectron-fasterrcnn-model-define/src/index.ts
- packages/plugins/model-define/detectron-maskrcnn-model-define/src/index.ts
- packages/plugins/model-define/tensorflow-mobilenet-model-define/src/index.ts
- packages/plugins/model-define/tensorflow-resnet-model-define/src/index.ts
- packages/plugins/model-define/tfjs-simplecnn-model-define/src/index.ts
Since now we change log.json to metadata.json and give labelmap inside dataset field. We need to change plugins accordingly
> fix path of metadata(labelmap) for several model define plugins

- packages/cli/package.json
- packages/cli/src/bin/pipcook.ts
- packages/plugins/model-evaluate/detectron-model-evaluate/src/index.ts
When the pipcook is not installed, package.json for daemon and pinboard does not exist, which will cause errors. Just to fix this
> cli: check if path exsits

- packages/cli/src/actions/start.ts
- packages/cli/src/bin/pipcook-pipeline.ts
- packages/cli/src/pipeline.ts
This improves the UX to run a pipeline in which plugins aren't installed.
> cli: prints the install logs

- README.md
- docs/INSTALL.md
- docs/zh-cn/INSTALL.md
- docs/zh-cn/manual/intro-to-pipeline.md
update how to use docker in doc.
> doc: update docker

- packages/boa/package.json
- packages/boa/tools/check-dependence.js
add dependence check before install.
> boa: add dependence check before install

- package-lock.json
- packages/boa/requirements.txt
- packages/daemon/package.json
1. removed the unnecessary `rxjs`
2. removed the boa's script "jieba" and "scikit-learn".
> daemon: remove unnecessary rxjs dep

- packages/plugins/data-collect/csv-data-collect/src/index.ts
- packages/plugins/data-collect/image-classification-data-collect/src/index.ts
- packages/plugins/data-collect/object-detection-coco-data-collect/src/index.ts
> plugins: update the glob wildcard to support more flexible searching for dataset

- tsconfig.json
This decreases re-compiling time.
> build: enable incremental build

- packages/plugins/model-train/image-classification-tfjs-model-train/src/index.ts
Use `tf.data.generator` to read in batches
> fix: ImageDataLoader OOM

- packages/costa/package.json
- run_tests.ts
fix issues: https://github.com/alibaba/pipcook/issues/319
> costa: fix test timeout

- packages/core/package.json
- packages/core/src/utils/public.ts
- packages/core/src/utils/public_test.ts
- packages/costa/package.json
- packages/costa/src/client.ts
- packages/costa/src/runnable.ts
- packages/costa/src/runtime.ts
- packages/daemon/package.json
- packages/daemon/src/runner/helper.ts
- packages/daemon/src/service/pipeline.ts
- packages/daemon/src/service/plugin.ts
- packages/plugins/data-access/csv-data-access/package.json
- packages/plugins/data-collect/csv-data-collect/src/index.ts
- packages/plugins/data-collect/image-classification-data-collect/package.json
- packages/plugins/data-collect/image-classification-data-collect/src/index.ts
https://github.com/alibaba/pipcook/issues/240
> daemon: refactor uuid to shortid

- packages/cli/src/request.ts
To reproduce the bug that this PR tries to fix, just run:
```sh
$ pipcook run https://foobar
```
> cli: correct the error message when receiving http errors.

- packages/core/src/utils/public_test.ts
This tries to handle https://github.com/alibaba/pipcook/runs/884522058's timeout errors as possible.
> core: increase the timeout for util tests

- packages/cli/assets/pluginPackage/src/modelDefine.ts
This PR is to address #362 that adds a template for `modelDefine` plugin.
> cli: add modelDefine template

- packages/sdk/package.json
Missing package `eventsource`.
> sdk: fix sdk dependence

- .github/workflows/cli.yml
- packages/daemon/src/runner/helper.ts
Check the package of pipeline config which is from 'http/https' protocol.
> daemon: throw error if the package is a local path and the pipeline config is from http/https url

- packages/core/src/types/data/common.ts
- packages/core/src/types/model.ts
This PR adds an interface that supports batched dataset
> Add dataset batch support

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/utils/public.ts
- packages/core/src/utils/public_test.ts
- packages/costa/package.json
- packages/costa/src/client.ts
- packages/costa/src/runnable.ts
- packages/costa/src/runtime.ts
- packages/daemon/package.json
- packages/daemon/src/runner/helper.ts
- packages/daemon/src/service/log-manager.ts
- packages/daemon/src/service/pipeline.ts
- packages/daemon/src/service/plugin.ts
- packages/plugins/data-access/csv-data-access/package.json
- packages/plugins/data-collect/image-classification-data-collect/package.json
- packages/plugins/data-collect/image-classification-data-collect/src/index.ts
As marked in #240 , the package `shortid` is dead, we need to replace with [nanoid](https://github.com/ai/nanoid).
> core: replace shortid with nanoid

- package.json
And we will generate our API documentation separately:
1. Pipcook SDK API
2. Pipcook Core API
> build, doc: remove deprecated typedoc-plugin-lerna

- package.json
This PR fixes the mismatch version issue
> build: add beta preid to version

- packages/daemon/src/migrations/20200803063219-addDatasetProcess.ts
We should  check if the table exists before migration.
> daemon: check table before migration

- packages/boa/tests/es-module-loaders/common.js
- packages/boa/tests/es-module-loaders/py/test-esm-loader-dynamic-imports.mjs
Refs: https://nodejs.org/api/esm.html#esm_import_expressions
/cc @yorkie @FeelyChau
> test(boa): add dynamic import test on esm

- .github/workflows/beta.yml
The beta release is down due to the lack of quotation marks.
> CI/CD: fix beta release

- packages/daemon/src/migrations/20200807132900-addPluginStatus.ts
> daemon: fix migration script

- packages/daemon/src/service/pipeline.ts
- test/pipelines/text-bayes-classification.json
- test/sdk/job.ts
Fix error when run `pipcook run config.json` with http/https/git protocol.
Test case updated.
> fix: error when run config file with http protocol

- packages/daemon/src/service/pipeline.ts
The output folder should be generated after the job has been updated
> daemon: generate output after job status updated

- packages/core/src/types/data/common.ts
- packages/core/src/types/data/common_test.ts
There is bug in dataloader:
the fetchIndex (pointer to current data) is not updated
> fix data batch

- docs/spec/plugin.md
- docs/zh-cn/spec/plugin.md
- packages/core/src/types/plugins.ts
- packages/daemon/templates/node/predict.js
Since we have changed how to data process works, need to change predict script accordingly
> fix data process to predict

- packages/app/package-lock.json
- packages/app/package.json
- packages/boa/package-lock.json
- packages/boa/package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/costa/package-lock.json
- packages/costa/package.json
- packages/daemon/package-lock.json
- packages/daemon/package.json
- packages/sdk/package-lock.json
- packages/sdk/package.json
- @pipcook/app@1.1.2
- @pipcook/boa@1.1.2
- @pipcook/pipcook-cli@1.1.2
- @pipcook/pipcook-core@1.1.2
- @pipcook/costa@1.1.2
- @pipcook/daemon@1.1.2
- @pipcook/sdk@1.1.2
> Bump version to 1.1.2

- README.md
- docs/manual/pipcook-tools.md
- docs/zh-cn/manual/pipcook-tools.md
- packages/cli/src/actions/init.ts
- packages/cli/src/bin/pipcook.ts
- packages/cli/src/types/handler.ts
Use `pipcook init 1.1.0` to install daemon and pipboard of v1.1.0.
> cli: init with version

- .github/workflows/release.yml
- docker/Dockerfile
This PR will includes:
- Build & Publish a Docker image after each version released.
- Installing a specified version for Pipcook from the tag.
> CI/CD: release Docker image

- docker/Dockerfile
> cli: optimize working directory of docker image

- packages/cli/src/service/job.ts
At this time, we can't know the pipeline info by job.
> cli: show pipeline id in job list

- docs/spec/plugin.md
- docs/zh-cn/spec/plugin.md
I will update to Chinese version when the English LGTY :)
> doc: add `pipcook.params` in spec documentation

- packages/daemon/src/service/log-manager.ts
- packages/daemon/src/service/trace-manager.ts
- packages/daemon/test/service/logpassthrough.test.ts
- packages/daemon/test/service/trace-manager.test.ts
- packages/daemon/test/service/tracer.test.ts
If no one subscribes the `data` event, the callback will not be called. See:
https://github.com/nodejs/node/blob/master/lib/_stream_transform.js#L37
> daemon: fix log missing

- .github/workflows/build.yml
- .github/workflows/markdown.yml
> ci: ignore draft pr

- .github/workflows/build.yml
- packages/cli/src/bin/pipcook-plugin.ts
- packages/cli/src/service/plugin.ts
- packages/cli/src/utils/common.ts
Support to install plugin from local tarball.
```sh
$ pipcook plugin install /path/to/tarball.tgz
```
> cli: plugin install from local tarball

- .yarnrc
- yarn.lock
This PR adds config to force yarn use npm registry only.
> build: use npm source

- docs/manual/intro-to-boa.md
- packages/boa/lib/delegators/builtins.enumerate.js
- packages/boa/lib/delegators/builtins.generator.js
- packages/boa/lib/delegators/callee.js
- packages/boa/lib/proxy.js
- packages/boa/src/core/object.cc
- packages/boa/tests/base/basic/__init__.py
- packages/boa/tests/base/delegator-builtins-generator.js
This PR adds generator support to align JS generator syntax
> boa: add generator support

- .circleci/config.yml
- tools/benchmark.sh
This PR adds supports for circleci benchmarking scripts
> bench: add config for circleCI

- .circleci/config.yml
This PR fixes the current CI script error by moving the condition statement to the workflow statement
> ci/cd: fix ciecle-ci script

- packages/daemon/src/app/controller/pipeline.ts
- packages/daemon/src/app/controller/plugin.ts
- packages/daemon/src/model/job.ts
- packages/daemon/src/model/pipeline.ts
- packages/daemon/src/model/plugin.ts
- packages/daemon/src/service/pipeline.ts
- packages/daemon/src/service/plugin.ts
- packages/daemon/test/controller/pipeline.test.ts
- packages/daemon/test/controller/plugin.test.ts
- packages/daemon/test/model/helper.ts
- packages/daemon/test/model/job.test.ts
- packages/daemon/test/model/pipeline.test.ts
- packages/daemon/test/model/plugin.test.ts
- packages/daemon/test/service/pipeline.test.ts
- packages/daemon/test/service/plugin.test.ts
Unit test for mode: `Job`,`Plugin`, `Pipeline`.
> daemon: add unit test for model

- docs/rfc/0001-framework-migration.md
- docs/rfc/0001-framework.md
> rfc: add rfc for framework migration

- docs/rfcs/0000-new-pipeline.md
> rfc: add new pipeline

- .github/workflows/beta.yml
- lerna.json
See https://github.com/lerna/lerna/issues/1560#issuecomment-412564396, it's a weird issue as the above mentioned, the yarn updates the registry which causes the authentication is failed.
> build: fix the beta release

- .github/workflows/build.yml
- .github/workflows/esbuild.yml
- .github/workflows/gh-pages.yml
- .github/workflows/markdown.yml
As we have migrated the default branch to main, thus this PR is to change the branch names to main as well :)
> meta: update the master branch to main in workflows

- docs/zh-cn/INSTALL.md
> docs: modify page typos

- .github/workflows/build.yml
- .github/workflows/esbuild.yml
- .github/workflows/markdown.yml
- packages/daemon/src/runner/job-runner.ts
- packages/daemon/test/utils/job-runner.test.ts
Fix bug: get the wrong job param for model-train plugin.
> daemon: fix job params

- packages/cli/package.json
- packages/daemon/package.json
- packages/sdk/package.json
- yarn.lock
> upgrade axios to 0.21.1

- tools/coverage.sh
The tool for coverage not exit with correct exit code if something wrong happened.
> workflow: fix error code of coverage tool

- packages/daemon/package.json
- packages/daemon/src/__tests__/unit/utils/index.test.ts
- packages/daemon/src/utils/index.ts
- yarn.lock
> daemon: remove dependency request

- .github/workflows/build.yml
use long version SHA for workflow action
> workflow: fix build workflow action

- packages/cli/package.json
- packages/cli/src/utils/index.ts
- yarn.lock
Beautify the download progress.
> cli: pretty download progress

- packages/cli/src/bin/pipcook.ts
- packages/cli/src/utils/framework.test.ts
- packages/cli/src/utils/framework.ts
- packages/cli/src/utils/index.ts
- packages/cli/src/utils/script.test.ts
- packages/cli/src/utils/script.ts
- yarn.lock
If the url in the pipeline meta is local path, we just copy it into workspace, it's useful for script developer.
> cli: fetch framework, script from local path

- packages/cli/.nycrc
- packages/cli/package.json
- packages/cli/src/constants/index.test.ts
- packages/costa/.nycrc
- packages/costa/package.json
- yarn.lock
1. fix coverage of cli
2. use ts-node to speedup test
> cli: fix coverage of constants

- .github/workflows/build.yml
- packages/cli/package.json
- packages/core/package.json
Remove unused dependency package `systeminformation` for  security.
> core: remove systeminformation

- packages/cli/src/bin/pipcook.ts
> fix<cli>: force output path to absolute

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/costa/package-lock.json
- packages/costa/package.json
- @pipcook/cli@2.0.0-rc.5
- @pipcook/core@2.0.0-rc.5
- @pipcook/costa@2.0.0-rc.5
> upgrade: publish 2.0.0-rc5

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/costa/package-lock.json
- packages/costa/package.json
- @pipcook/cli@2.1.0
- @pipcook/core@2.1.0
- @pipcook/costa@2.1.0
> bump version: v2.1.0

- .github/workflows/build.yml
- packages/cli/src/bin/pipcook.ts
Only one alias could be set to the command.
> cli: fix command alias

- packages/cli/package.json
- packages/core/package.json
- packages/costa/package.json
Bug fix:
- command `train` is not available.
> bump: v2.2.1

- notebooks/pipcook_object_detection.ipynb
Fix dataset URL in the notebook.
> notebook: fix link

- packages/cli/src/bin/pipcook.ts
- packages/cli/src/utils/index.ts
#768  Optimize folder name for `train` .
> cli: set default output directory to `pipcook-output-{hhmmss}`

- tools/benchmark.sh
> meta: fix benchmark tool

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/costa/package-lock.json
- packages/costa/package.json
- @pipcook/cli@2.1.4
- @pipcook/core@2.1.4
- @pipcook/costa@2.1.4
> bump version: 2.1.4
