- Dockerfile
tfjs is using cuda 10.0, whereas detectron2 using 10.1.
we need support both
> added cuda 10.0 for tfjs

- packages/pipcook-cli/assets/pluginPackage/src/dataAccess.ts
- packages/pipcook-cli/assets/pluginPackage/src/dataCollect.ts
- packages/pipcook-cli/assets/pluginPackage/src/dataProcess.ts
- packages/pipcook-cli/assets/pluginPackage/src/modelDeploy.ts
- packages/pipcook-cli/assets/pluginPackage/src/modelEvaluate.ts
- packages/pipcook-cli/assets/pluginPackage/src/modelLoad.ts
- packages/pipcook-cli/assets/pluginPackage/src/modelTrain.ts
The cast in `<T>` is not recommended because it's conflicts with jsx/tsx syntax.
See:
- https://palantir.github.io/tslint/rules/no-angle-bracket-type-assertion/
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-assertions.md
> cli: fix the type casts by `as` keyword

- packages/pipcook-app/src/models/objectDetection.ts
The changed lines are inconsistent with
https://github.com/alibaba/pipcook/blob/715f3355bb08c2109228f07c4f5341f0bb268824/packages/pipcook-app/src/models/objectDetection.ts#L26
and it's recommended to use the sign `;` as the terminated.
> pipcook-app: fix the interface member ends

- README.md
Without the links to examples, it's hard to direct developers to run these examples, so this PR adds these links firstly, and it also describes these examples in the README are subset of our complete example list.
> readme: refine the description and add links to run pipeline section

- .eslintrc.js
This PR changes the eslint rules extending some recommended ones:
- `eslint:recommended`
- `plugin:@typescript-eslint/eslint-recommended`
- `plugin:@typescript-eslint/recommended`
The result for the current codebase is:
```sh
620 problems (207 errors, 413 warnings)
```
But never mind, I'll create some other PRs to fix these errors and warnings, once all is gone, the CI is able to work for us.
> meta, lint: extends the recommended rules

- .eslintignore
- .eslintrc.js
- package.json
- packages/pipcook-python-node/src/communication/communication.ts
- packages/pipcook-python-node/src/core/python-helper.ts
This changes some lint infra like:
- script name to "lint"
- add .eslintignore
> build: fix the python-node package lint errors

- .eslintrc.js
- packages/pipcook-core/src/board/board.ts
- packages/pipcook-core/src/core/core-helper.ts
- packages/pipcook-core/src/core/core.ts
- packages/pipcook-core/src/index.ts
- packages/pipcook-core/src/types/component.ts
- packages/pipcook-core/src/types/data.ts
- packages/pipcook-core/src/types/other.ts
- packages/pipcook-core/src/types/plugins.ts
- packages/pipcook-core/src/utils/serverProcess.ts
Escape is always good, so it disables the rule "no-useless-escape", too.
> build: fix pipcook-core lint errors

- packages/pipcook-core/src/types/component.ts
See https://github.com/alibaba/pipcook/blob/master/packages/pipcook-core/src/core/core-helper.ts#L138, it iterators `mergeComponents` for `PipcookComponentResult[]` instead of `PipcookComponent[]`, I'm not sure why tsc ignore this, but it gets fixed now and removed the interface `PipcookComponent`.
> core: remove the unused interface and fix type

- docs/_navbar.md
- docs/zh-cn/_navbar.md
- typedoc.json
This changes the mode to file and fixes links to API References.
> build, doc: fix the typedoc mode to file

- packages/core/src/constants/plugins.ts
- packages/core/src/types/config.ts
- packages/core/src/types/plugins.ts
1. Move the `PluginTypeI` into types.
2. Simplify the `RunConfigI` interface.
> core: simplify the RunConfigI definitions

- README.md
'or' is inaccurate here, install dependencies is required.
> docs: fix Inaccurate expression.

- packages/boa/binding.gyp
This is to fix #99 which is a compiler error on Node.js 10.13.x~10.15.x, because there is a weird setup for NAPI_VERSION with NAPI_EXPERINMENT, and node-addon-api will not handle that, I have a root fix at https://github.com/nodejs/node-addon-api/pull/703.
But let's have this land to fix #99 ASAP.
> build: specify NAPI_VERSION to fix the node-addon-api issue

- packages/core/src/runner/helper.ts
- packages/core/src/types/other.ts
- packages/plugins/model-evaluate/bayesian-model-evaluate/src/index.ts
- packages/plugins/model-evaluate/image-classification-tfjs-model-evaluate/src/index.ts
- packages/plugins/model-evaluate/object-detection-detectron-model-evaluate/src/index.ts
- test/pipelines/text-bayes-classification.json
This fixes #129 by introducing a pass field on `EvaluateResult` interface, the core will throw a corresponding `EvaluateError` when this field is not set true.
> plugin, core: fail the pipeline when evaluation is not pass

- packages/core/src/components/lifecycle.ts
- packages/core/src/types/other.ts
- packages/core/src/types/plugins.ts
fix [#72](https://github.com/alibaba/pipcook/issues/72)
**details**
- Replace `any` for pipcook plugin params with the existing `PipObject`
- Remove `any` that could be inferred by other definition
- Use TypeScript built-in generic types first
> core: remove `any` types for `lifecycle.ts`

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/utils/public.ts
- packages/core/src/utils/public_test.ts
the converter from pascal to coco has some problems where the id of image is not corresponding to image_id in annotations. Just to fix it
> core: correct the coco's id in public utils

- packages/core/src/runner/helper.ts
- packages/plugins/model-evaluate/object-detection-detectron-model-evaluate/package-lock.json
- packages/plugins/model-evaluate/object-detection-detectron-model-evaluate/package.json
- packages/plugins/model-evaluate/object-detection-detectron-model-evaluate/src/index.ts
This PR includes
- only if the evaluate pass return false, the core will throw errors
- the dataset in detectron evaluate should be 'test_dataset'
> fix evaluate pass check and a bug in plugin

- packages/core/src/components/lifecycle.ts
- packages/core/src/runner/helper.ts
- packages/core/src/types/component.ts
- packages/core/src/types/other.ts
- packages/core/src/types/plugins.ts
- packages/core/src/types/utility.ts
fix [#72](https://github.com/alibaba/pipcook/issues/72)
**details**
- Add custom generic tool `PromisedValueOf`
- Remove `any` of observable in plugin's lifecycle
> core: remove `any` of plugin's lifecycle

- packages/core/src/constants/other.ts
- packages/core/src/constants/other_test.ts
- packages/core/src/constants/plugins.ts
- packages/core/src/constants/plugins_test.ts
- packages/core/src/runner/helper.ts
- packages/core/src/runner/index.ts
- packages/core/src/types/component.ts
- packages/core/src/types/other.ts
- packages/core/src/types/plugins.ts
Deployment has been removed from plugins and packaged into the core(#117), but there are still some useless strategies or definitions of deploy plugin left, this PR will remove it
> core: purge deploy stage from plugins

- packages/core/src/components/lifecycle.ts
- packages/core/src/constants/other.ts
- packages/core/src/constants/other_test.ts
- packages/core/src/runner/helper.ts
- packages/core/src/runner/index.ts
- packages/core/src/types/component.ts
This PR improves the type of `updateType` that mentioned at #177 
- Adding type definition of the output type
- remove useless status constants
> core: add type definition of the ouput type

- .github/workflows/build.yml
- .travis.yml
- appveyor.yml
- docs/tutorials/want-to-use-python.md
- docs/zh-cn/tutorials/want-to-use-python.md
- packages/boa/esm/loader.mjs
- packages/boa/package.json
- packages/boa/tests/es-module-loaders/common.js
- packages/boa/tests/es-module-loaders/js/test-esm-loader-custom.mjs
- packages/boa/tests/es-module-loaders/js/test-esm-loader-math.mjs
- packages/boa/tests/es-module-loaders/js/test-esm-loader-thirdparty.mjs
- packages/boa/tests/es-module-loaders/py/test-esm-loader-custom.mjs
- packages/boa/tests/es-module-loaders/py/test-esm-loader-stdlib.mjs
- packages/boa/tests/es-module-loaders/py/test-esm-loader-thirdparty.mjs
fixes: #173 
Support `export default` and `named export` import.
/cc @yorkie
> boa: support esm

- packages/boa/src/binding.cc
将模块名称由硬编码修改为NODE_GYP_MODULE_NAME宏，确保会将最终二进制文件的名称传给 NODE_MODULE()
> Boa: 将模块名称由硬编码修改为 NODE_GYP_MODULE_NAME 宏

- package.json
- packages/costa/package.json
- packages/costa/src/index.ts
- packages/costa/src/runnable_test.ts
- packages/costa/src/runtime.ts
- packages/costa/src/runtime_test.ts
- run_tests.ts
This supports the beta and specific version for plugin installation:
- `@pipcook/my-plugin`
- `@pipcook/my-plugin@latest`
- `@pipcook/my-plugin@beta`
- `@pipcook/my-plugin@1.0.0`
> costa: support beta version for installing plugin

- packages/daemon/src/service/plugin.ts
We should uninstall the plugin if the installation is failed finally.
> daemon: cleanup if installing a package is failed

- packages/boa/lib/index.js
- packages/boa/package.json
The CPython is a single instance, so we need to keep consistent with CPython by storing its instance globally.
This fixes the issue "python interrupter is already running" when loading the boa in different plugins.
> boa: share the cpython instance globally

- packages/cli/src/actions/init.ts
Now that we do not allow tnpm in config. It's not necessary to force to fetch from official registry. cnpm mirror should also be allowed.
> Do not specify registry

- packages/cli/src/actions/init.ts
There was a file operation error while `pipcook init`, fix it.
> cli: fix pipcook init error

- docs/manual/pipcook-tools.md
- docs/zh-cn/manual/pipcook-tools.md
- packages/costa/package.json
- packages/costa/src/index.ts
- packages/costa/src/runtime.ts
Installing a plugin from git via ssh is an easy way to share plugins, now we could install the plugin and write pipeline in the following way:
```
{
"plugins": {
"dataCollect": {
"package": "git+ssh://git@gitlab.com/repo.git"
}
}
}
```
> costa: support install plugin from git(ssh)

- packages/costa/package.json
There is a build error here:
``` shell
src/runtime.ts:4:17 - error TS7016: Could not find a declaration file for module 'tar-stream'. 'pipcook/packages/costa/node_modules/tar-stream/index.js' implicitly has an 'any' type.
Try `npm install @types/tar-stream` if it exists or add a new declaration (.d.ts) file containing `declare module 'tar-stream';`
```
> costa: add dependency @type/tar-stream

- docker/Dockerfile
- packages/plugins/data-collect/csv-data-collect/package.json
- packages/plugins/data-collect/csv-data-collect/src/index.ts
- packages/plugins/data-collect/image-classification-data-collect/package.json
- packages/plugins/data-collect/image-classification-data-collect/src/index.ts
- packages/plugins/data-collect/mnist-data-collect/package.json
- packages/plugins/data-collect/mnist-data-collect/src/index.ts
- packages/plugins/data-collect/object-detection-pascolvoc-data-collect/package.json
- packages/plugins/data-collect/object-detection-pascolvoc-data-collect/src/index.ts
This PR includes:
1. Currently in data collect plugins, we do not clear the data folder, which results in mixture of different datasets. We can firstly remove folder for now. In the future, the data-collect plugin should be responsible for checking if the dataset url is changed or if the data content is changes and decide whether just ignore current dataset or download new one.
2. We need cuda 10.1 and cuda 10.2 in dockerfile. not 10.0 and 10.1
> modify dockerfile and data collect

- packages/daemon/src/service/pipeline.ts
- packages/pipboard/src/layouts/BasicLayout/index.jsx
- packages/pipboard/src/layouts/BasicLayout/index.scss
- packages/pipboard/src/pages/Pipeline/index.jsx
- packages/pipboard/src/pages/Pipeline/index.scss
- packages/pipboard/src/utils/config.js
For Pipeline View:
> Only show the dataset and model, and also added the jobs by pipeline id.
For Job View:
> Optimize the cell styles and add model download feature.
> pipboard: simplify the pipboard list view

- packages/cli/src/actions/start.ts
- packages/cli/src/bin/pipcook-job.ts
- packages/cli/src/bin/pipcook.ts
- packages/cli/src/pipeline.ts
Now we support generating the output dir in a specific name:
```bash
$ pipcook run foobar.json --output my-model
```
> cli: support custom output dir

- packages/daemon/src/app/controller/index.ts
The current index(/) route returns 404, this changes to redirect to `/index.html`.
> daemon: redirect to index.html for default router

- packages/cli/src/bin/pipcook-daemon.ts
- packages/daemon/bootstrap.js
This optimizes the logs when the daemon starts failed:
- checking if the daemon is running via pidfile.
- outputs the access log when it failed.
- handles the daemon `exit`.
> cli: optimize the pipcook-daemon error

- packages/cli/src/actions/init.ts
This will run `npm init` before installing daemon and board, it will generate the package.json to avoid the npm node_modules downgrading, such as if there is a node_modules at `~/node_modules`, so all the pipcook packages will be installed at `~/node_modules` instead of `~/.pipcook`.
> cli: run `npm init` for daemon/pipboard to avoid npm downgrading

- packages/plugins/model-train/image-generation-tensorflow-model-train/package.json
The plugin "image-generation-tensorflow-model-train" doesn't use the `boa` package, just remove it.
> plugin: remove unneeded boa dep

- packages/boa/package.json
- packages/boa/pybind11/Makefile
After `npm install` for boa, there is a download directory left, should be removed.
> boa: clean tmp files for pybind11 after make

- docs/manual/pipcook-tools.md
- docs/zh-cn/manual/pipcook-tools.md
- packages/cli/src/bin/pipcook-daemon.ts
Typing the daemon directory path should be not that easy, this PR adds a new command `daemon debug`, which starts the service in current process, it simplifies debugging when sometimes we want users to start the daemon manually.
> cli: add new command `daemon debug` for debugging the daemon service

- packages/cli/src/bin/pipcook-daemon.ts
The current by-default kill causes the costa process is still running after the daemon is killed by cli, thanks @lewis617 for catching this :p
> cli: daemon-stop use SIGINT as the default signal.

- packages/plugins/data-collect/csv-data-collect/package.json
This fixes the problem:
```sh
2020-07-08 20:57:33,032 ERROR 30029 nodejs.TypeError: Cannot find module 'fs-extra'
Require stack:
- /Users/yorkie/.pipcook/plugins/node_modules/@pipcook/plugins-csv-data-collect/dist/index.js
- /Users/yorkie/workspace/pipcook/packages/costa/dist/client.js
Require stack:
- /Users/yorkie/.pipcook/plugins/node_modules/@pipcook/plugins-csv-data-collect/dist/index.js
- /Users/yorkie/workspace/pipcook/packages/costa/dist/client.js
at PluginRunnable.<anonymous> (/Users/yorkie/workspace/pipcook/packages/costa/dist/runnable.js:139:23)
at Generator.next (<anonymous>)
at fulfilled (/Users/yorkie/workspace/pipcook/packages/costa/dist/runnable.js:5:58)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
> plugin: fix the dependencies for fs-extra

- packages/daemon/templates/boapkg.js
This makes someone think it's broken, actually run `node index.js` is ok.
> daemon: dont print the boa not found stacktrace

- packages/costa/benchmark/bootstrap.js
- packages/costa/benchmark/makefile
To run the bootstrap benchmark for costa:
```sh
$ cd packages/costa
$ make -C benchmark
time node ./bootstrap.js
costa.runnable make sure the component dir is existed. +0ms
costa.runnable bootstrap a new process for c00b5cf0-c26f-11ea-93dc-2165bcacf22a. +4ms
costa.runnable sent handshake for c00b5cf0-c26f-11ea-93dc-2165bcacf22a, and wait for response +9ms
costa.runnable the runnable(c00b5cf0-c26f-11ea-93dc-2165bcacf22a) has been destroyed with(code=0, signal=null). +106ms
0.44 real         0.40 user         0.08 sys
```
> costa: add bootstrap script for bootstrap

- packages/daemon/src/boot/database.ts
- packages/pipboard/src/utils/config.js
Reported by @zhaoleipeng, there are some cases in which the evaluateMap is not an object.
> pipboard: fix the job which evaluateMap.pass is not accessible

- packages/costa/src/client.ts
- packages/costa/src/runtime.ts
- packages/costa/src/runtime_test.ts
- packages/plugins/model-train/bayesian-model-train/package.json
This provides a specific path for pip's `--cache-dir`, it fixes not caching in PC where the pip's cache environment not getting set up.
> costa: use ~/.pipcook/plugins/.pip as the default cache dir

- packages/boa/.eslintrc.js
- packages/boa/tests/es-module-loaders/common.js
See https://github.com/nodejs/node/pull/33501, At Node.js 14.5.0, it removes the dynamic module format, so we need to make compatible works for the new with esm loader.
Node.js Release PR: https://github.com/nodejs/node/pull/34093
> boa: skip the esm tests for node >= 14.5.0

- .github/workflows/pipeline.yml
Our current pipeline builds are failed, see https://github.com/alibaba/pipcook/runs/871744946?check_suite_focus=true. Just fix this by adding `pipcook daemon start`.
> build: fix the pipeline action

- packages/boa/lib/index.js
Remove annotation for `no-process-env`, because the rule has been disabled.
> boa: remove no-process-env disable annotation

- packages/daemon/templates/node/predict.js
Currently, the script 'preidct.js' is generated to output folder when the pipeline is finished. However, in predcit.js, data process method's promise is not resolved before the model starts to predict, which causes problems. This PR is to fix this.
This problem causes error when we predict tfjs image classification:
```
ValueError: Error when checking : expected conv2d_Conv2D1_input to have shape [null,28,28,3] but got array with shape [1,1440,1080,3].
```
> fix predict script

- packages/pipboard/src/components/Card/index.jsx
- packages/pipboard/src/pages/Home/index.jsx
- packages/pipboard/src/pages/Pipeline/PipelineInfo/components/LogView/index.jsx
- packages/pipboard/src/pages/Tutorial/index.jsx
The eslint-plugin-react@7.20.4 introduced a crash bug when linting a source with an anonymous function with the ES modules. This PR removes all related anonymous functions to hotfix the problem.
See https://github.com/yannickcr/eslint-plugin-react/issues/2728 for more information.
> pipboard: fix the lint crash by eslint-plugin-react

- packages/boa/tools/install-python.js
The latest miniconda has switched to Python 3.8 :)
> boa: use the specific version to fix build failure

- packages/core/src/utils/public_test.ts
`fs.rmdir` fails if the target directory is not empty, using `fs.remove` instand.
> core: fix test error

- package.json
This PR fixes the skipping behavior for `beta` release.
And changed the preid for beta release to `beta`
> CI/CD: fix beta release skipping

- lerna.json
- package-lock.json
- package.json
- packages/costa/package-lock.json
- packages/pipboard/package-lock.json
- packages/pipboard/package.json
- packages/sdk/package-lock.json
This fixes #344, and the `node_modules` result is:
| before | after |
|--------|------|
| 1.3G | 826M |
> build: tweak the versions to decrease root packages' size

- packages/boa/pybind11/Makefile
When I execute `$ learn add some-package --scope @pipcook/pipcook-core`, the dependence of boa `pybind11` was downloaded again.
> boa: fix redownload pybind11 when execute `lerna add`

- packages/boa/lib/index.js
- packages/boa/src/core/object.cc
- packages/boa/tests/base/basic.js
- packages/boa/tests/base/basic/__init__.py
- packages/boa/tests/stdlib/builtins.js
- packages/plugins/model-define/tensorflow-cycle-gan-model-define/src/index.ts
- packages/plugins/model-train/image-generation-tensorflow-model-train/package.json
- packages/plugins/model-train/image-generation-tensorflow-model-train/src/index.ts
It creates a new class and instantiates it with given props when passing to Python. For example:
```js
pythonfunc({ foobar: 10 });
```
At Python, we have to write in this way:
```py
def func(opt):
opt.get('foobar') # 10, because opt is a dict
```
Within this Pull Request, the developer is able:
```py
def func(opt):
opt.foobar
```
Otherwise, I also removed an incorrect case:
```js
const o = { foobar: 10 };
len(o); // not working
len(dict(boa.kwargs(o))); // working
```
Even though it's more complexed than before, but it's more correct way to be used.
> boa: generate object instead of `dict` to Python function

- package.json
This PR adds `clean` ahead of install process to avoid extremely long `prune hoisting ` time.
For more detail, please refer to this issue https://github.com/lerna/lerna/issues/602
> build: re-installation takes too long

- docs/contributing/contribute-a-plugin.md
- docs/zh-cn/contributing/contribute-a-plugin.md
- docs/zh-cn/spec/plugin.md
- packages/costa/package.json
- packages/costa/src/client/entry.ts
- packages/costa/src/client/loaders/index.ts
- packages/costa/src/client/loaders/nodejs.ts
- packages/costa/src/client/loaders/python.ts
- packages/costa/src/index.ts
- packages/costa/src/runnable.ts
- packages/costa/src/runtime.ts
- packages/costa/test/lrucache_test.ts
- packages/costa/test/plugins/nodejs-simple/index.js
- packages/costa/test/plugins/nodejs-simple/package.json
- packages/costa/test/plugins/python-simple/__init__.py
- packages/costa/test/plugins/python-simple/package.json
- packages/costa/test/protocol_test.ts
- packages/costa/test/runnable_test.ts
- packages/costa/test/runtime_test.ts
- packages/costa/tsconfig.json
In order to better attract machine learning developers to contribute models to Pipcook, this PR provides developers with a native Python development environment. For users who do not use Node.js and JavaScript, they can use pure Python to write plugins.
> costa: add python runnable for machine-learning developers

- .github/workflows/beta.yml
- package.json
This pr uses `build_id` instead of `beta` as the preid to fix the package name issue
> CI/CD: Fix prerelease

- packages/costa/test/plugins/python-simple/package.json
- packages/plugins/data-process/tensorflow-image-classification-process/package.json
- packages/plugins/model-define/bayesian-model-define/package.json
- packages/plugins/model-define/detectron-fasterrcnn-model-define/package.json
- packages/plugins/model-define/detectron-maskrcnn-model-define/package.json
- packages/plugins/model-define/tensorflow-cycle-gan-model-define/package.json
- packages/plugins/model-define/tensorflow-mobilenet-model-define/package.json
- packages/plugins/model-define/tensorflow-resnet-model-define/package.json
- packages/plugins/model-evaluate/bayesian-model-evaluate/package.json
- packages/plugins/model-evaluate/detectron-model-evaluate/package.json
- packages/plugins/model-evaluate/image-classification-tensorflow-model-evaluate/package.json
- packages/plugins/model-load/tensorflow-model-load/package.json
- packages/plugins/model-train/bayesian-model-train/package.json
- packages/plugins/model-train/detectron-model-train/package.json
- packages/plugins/model-train/image-classification-tensorflow-model-train/package.json
The latest version of opencv-python is 4.3.0.38, but it costs too much time to build, so we lock it at 4.3.0.36.
> plugins: lock the version of python dependencies

- packages/costa/src/runtime.ts
- packages/daemon/src/app/controller/pipeline.ts
- packages/daemon/src/service/pipeline.ts
- packages/daemon/src/service/plugin.ts
If any plugin is not installed, `daemon` will throw 404 error with the message includes the uninstalled plugin list.
> daemon, costa: remove the installation action for job run

- .github/workflows/cli.yml
- packages/cli/src/bin/pipcook.ts
- packages/cli/src/service/job.ts
Bug fix:
The command `pipcook run <config file>` did not download the output.
> cli: fix run a pipeline config without download

- packages/daemon/package.json
Fix: #449 
MacOS Catalina 10.15.5 MacBook Pro (16-inch, 2019)
Node: v12.17.0
```shell
$ node ./packages/daemon/bootstrap.js
npx: 80 安装成功，用时 30.633 秒
single process mode is still in experiment, please don't use it in production environment
Server is listening at http://localhost:6927, cost 35.354666849s
```
```shell
$ node ./packages/daemon/bootstrap.js
single process mode is still in experiment, please don't use it in production environment
Server is listening at http://localhost:6927, cost 3.240450431s
```
> daemon: preinstall sequelize-cli for migration

- packages/daemon/src/service/plugin.ts
- packages/sdk/src/utils.ts
The plugin status is missing if the plugin is installing or pending by command `pipcook plugin list`.
> daemon: fix plugin status

- packages/cli/src/actions/init.ts
- packages/cli/src/config.ts
Speed up the plugin installation.
Benchmark:
Before: 1.16s user 0.26s system 0% cpu 4:08.73 total
```shell
$ time ./packages/cli/dist/bin/pipcook pipeline install ./example/pipelines/text-bayes-classification.json --tuna
ℹ Wrote to /path/.pipcook/plugins/package.json:
ℹ fetching package info @pipcook/plugins-csv-data-collect
ℹ {
ℹ   "name": "plugins",
ℹ   "version": "1.0.0",
ℹ   "description": "",
ℹ   "main": "index.js",
ℹ   "scripts": {
ℹ     "test": "echo \"Error: no test specified\" && exit 1"
ℹ   },
ℹ   "keywords": [],
ℹ   "author": "",
ℹ   "license": "ISC"
ℹ }
ℹ fetching package info @pipcook/plugins-csv-data-collect
ℹ fetching package info @pipcook/plugins-csv-data-collect
......
ℹ check plugin:
✔ @pipcook/plugins-csv-data-collect installed.
✔ @pipcook/plugins-csv-data-access …
```
> cli: init plugin with boa and core

- .github/workflows/build.yml
- packages/cli/src/service/pipeline.ts
The command `pipcook pipeline install /path/to/pipeline.json` finish with error, and CI did not check out this, because the plugins in the case are all installed before.
> cli: fix plugin install error, fix ci test case

- packages/costa/benchmark/makefile
- packages/costa/benchmark/plugin-install.js
- packages/costa/src/runtime.ts
- packages/costa/src/utils.ts
Benchmark:
Test command:
```shell
$ time ./packages/cli/dist/bin/pipcook plugin install @pipcook/plugins-tensorflow-resnet-model-define --tuna
```
This plugin depends on `tensorflow@2.2.0`.
| Branch                       | Test A          | Test B          | Test C          | Test D          | AVG             |
| ---------------------------- | --------------- | --------------- | --------------- | --------------- | --------------- |
| master                       | 1 m 20.06 s | 1 m 19.86 s | 1 m 25.03 s | 1 m 18.33 s | 1 m 20.82 s |
| modify/parallel-installation | 1 m 11.06 s | 1 m 04.47 s | 1 m 04.92 s | 1 m 11.27 s | 1 m 07.93 s |
In this typical scenario, reduced installation time by 15%.
> costa: install Node and Python packages in parallel

- package.json
- packages/daemon/tsconfig.json
Daemon is an executable so that the d.ts is unnecessary, this PR sets declaration to `false` to avoid this.
> daemon: avoid generating d.ts files

- lerna.json
- packages/daemon/package-lock.json
- packages/daemon/package.json
- packages/daemon/src/config/config.default.ts
- packages/daemon/src/config/plugin.ts
Our next-generation board will be an absolute web-based application, so we need a CORS setting on daemon for that access to the local/remote Pipcook via SDK.
> daemon: enable cors for ng-pipboard

- packages/cli/tsconfig.json
See #494, the cli might not need these declaration files.
> cli: avoid generating d.ts

- packages/daemon/package.json
No need to use npx to wrap the command in npm-script.
> daemon: remove unneeded npx from npm-script

- packages/sdk/package.json
Without this, the TypeScript language service would give an error on the `tsconfig.json` because "../../tsconfig.json" is not found.
> sdk: specify files in package to avoid tsconfig error

- packages/costa/src/client/loaders/python.ts
- packages/costa/test/plugins/python-scope/__init__.py
- packages/costa/test/plugins/python-scope/package.json
- packages/costa/test/runnable_test.ts
When the plugin specifies 'python' runtime, boa will try to import plugin's entry python file. 
Right now it imports like:
```
const fn = boa.import(`node_modules.${pkg.name}`);
```
However, if the plugin name includes scope, for instance:
```
@pipcook/ner_model
```
the contents inside import will be
```
node_modules.@pipcook/ner_model
```
The right way to import should be:
```
node_modules.@pipcook.ner_model
```
This PR is to fix this
> fix python runtime

- packages/cli/src/service/plugin.ts
This log is not needed to be printed when uninstalling a plugin.
> cli: remove unneeded log

- packages/costa/src/client/entry.ts
Costa process should handle the promise reject in nextTick.
```shell
ℹ start loading plugin @pipcook/plugins-image-classification-data-collect
ℹ downloading dataset ...
ℹ unzip and collecting data...
ℹ create annotation file...
ℹ start loading plugin @pipcook/plugins-pascalvoc-data-access
ℹ create a result "1dbgsib6" for plugin "@pipcook/plugins-pascalvoc-data-access@1.1.0"
ℹ start loading plugin @pipcook/plugins-image-data-process
ℹ start loading plugin @pipcook/plugins-tensorflow-mobilenet-model-define
⚠ (node:55539) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
⚠     at DataLoader.<anonymous> (/path/to/.pipcook/plugins/node_modules/@pipcook/plugins-pascalvoc-data-access/dist/index.js:63:47)
⚠     at Generator.next (<anonymous>)
⚠     at …
```
> fix: child process not exits with unhandled rejection

- packages/daemon/src/migrations/20200825183100-addPluginId.ts
If the old db has pipelines and plugins, the migration script will add the columns and update the plugin id columns which plugin exists in the plugin table.
> daemon: update it when add plugin id columns in pipeline table

- packages/cli/src/actions/init.ts
- packages/cli/src/config.ts
We have completely moved the pipboard to a separate repository [imgcook/pipboard][], this PR removes the pipboard from initialization that decreases by 10s.
[imgcook/pipboard]: https://github.com/imgcook/pipboard
> cli: remove pipboard from core and cli

- packages/cli/src/bin/pipcook-job.ts
- packages/cli/src/service/job.ts
run from pipeline id not work now.
```sh
$   pipcook job run 8mxmozos
✖ something wrong when run job: /home/admin/.pipcook/server/8mxmozos not exists
```
> cli: fix run from pipeline id

- packages/sdk/src/utils.ts
```sh
┌─────────┬────────────┬────────────┬───────────┬──────────────┬────────────────────────────┐
│ (index) │     id     │ pipelineId │  status   │ evaluatePass │         createdAt          │
├─────────┼────────────┼────────────┼───────────┼──────────────┼────────────────────────────┤
│    0    │ 'tvc9wx0e' │ 'ho86xso5' │ undefined │     null     │ '2020-09-03T12:17:49.977Z' │
│    1    │ 'a9dcm7ny' │ '8v59hnhe' │ 'running' │     null     │ '2020-09-03T12:17:43.038Z' │
└─────────┴────────────┴────────────┴───────────┴──────────────┴────────────────────────────┘
```
> cli: fix job pending status missing

- packages/daemon/src/app/controller/pipeline.ts
- packages/daemon/test/controller/pipeline.test.ts
If run a pipeline with plugins which from http url, there will be a 404 error from npm.
> daemon: fix pipeline create

- packages/daemon/src/app/controller/job.ts
- packages/daemon/test/controller/job.test.ts
Fix: if a job is not successful, or the output file not exists, the api `download` should return 400 and error message.
And add tests for it.
> daemon: add tests for job download

- packages/daemon/src/app/controller/job.ts
- packages/daemon/test/controller/index.test.ts
- packages/daemon/test/controller/job.test.ts
- packages/daemon/test/controller/pipeline.test.ts
Improve `Job` and `Pipeline` controllers coverage to  [ 100%, 100% ] from [ 67.69%, 57.69%].
> daemon: improve coverage for controller

- packages/daemon/package.json
- packages/daemon/src/app/controller/plugin.ts
- packages/daemon/test/controller/app.test.ts
- packages/daemon/test/controller/base.test.ts
- packages/daemon/test/controller/job.test.ts
- packages/daemon/test/controller/log.test.ts
- packages/daemon/test/controller/playground.test.ts
- packages/daemon/test/controller/plugin.test.ts
Improve `App`, `Base`, `Log`, `Playground`, `Plugin` controllers coverage:
> daemon: add test for controllers

- packages/costa/src/client/entry.ts
- packages/costa/src/runnable.ts
- packages/costa/test/plugins/nodejs-simple/index.js
- packages/costa/test/runnable_test.ts
Fix #561 .
Costa sends the destroy-request by IPC, if the client is busy, i.e. training loop in boa stack, the request will not be processed util the `nextTick`, so it will not exit immediately. But we can use signal to make sure the client process can receive it when the OS switches the process from sleeping to running.
> costa: send signal instead of ipc to destroy client

- .github/workflows/pipeline.yml
Currently, the CI machine to run pipeline only has 4G memory. This is not enough for BERT model. This PR is to stop this pipeline's daily run temporarily. For the future, we need to transfer our pipeline run to our own machine or to other CI services
> ci: delete daily run of NER pipeline

- docker/Dockerfile
Fix:
```sh
[tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.2/lib64:/opt/rh/rh-nodejs12/root/usr/lib64
```
> docker: fix cuda environment

- packages/boa/pybind11/Makefile
- packages/boa/tools/check-network-env.js
Cloudflare provides an API to get the location, we use this API to select the pybind mirror automatically, and the improvements are evident for my location.
__before__
```
$ DISABLE_AUTO_SWITCH=1 time make -C pybind11
49.62 real         0.14 user         0.16 sys
26.11 real         0.06 user         0.12 sys
37.36 real         0.07 user         0.14 sys
33.38 real         0.07 user         0.15 sys
45.23 real         0.08 user         0.16 sys
avg: 38.33
```
__after__
```
$ time make -C pybind11
2.14 real         0.12 user         0.12 sys
1.78 real         0.11 user         0.14 sys
1.34 real         0.09 user         0.15 sys
3.40 real         0.10 user         0.14 sys
1.48 real         0.10 user         0.15 sys
avg: 2.03
```
> Note: added an env `DISABLE_AUTO_SWITCH` to manually …
> boa: use Cloudflare geo api to select mirror automatically

- .yarnrc
As title suggests, this pr is to avoid timeout while installing packages in github action
> CI/CD: Add yarn timeout config to avoid npm install timeout          

- packages/daemon/package.json
- packages/daemon/src/model/job.ts
- yarn.lock
This PR upgrades sequelize to 6.x to get support for JSON.
See #628
> dependencies, daemon: Upgrade sequelize

- packages/boa/binding.gyp
- packages/boa/tools/install-python.js
- packages/boa/tools/utils.js
This fixes #639, it's caused by the current miniconda doesn't compile its stdlib for macOS BigSur. With this patch, we are only to use the CPython libraries only when linking dynamically.
> boa: avoid to set @rpath to conda which includes incompatible stdlib

- CODEOWNERS
This adds the CODEOWNERS file to specify the src owners.
> meta: add CODEOWNERS

- README.md
We have migrated the Pipboard from vercel to GitHub pages, this corrects the pipboard URI.
> doc: fix the pipboard url

- packages/costa/src/runnable.ts
We should set the callback when call `subprocess.send` for catching the asynchronous error.
> costa: catch the error when subprocess send failed

- packages/core/src/types/other.ts
Refer to issue #585 
We need to support the evaluation result for both the train and test dataset. This PR is to support this case from the view of core spec. Meanwhile, we will change the plugins to support this feature.
> core: add detail spec for evaluate result

- .github/workflows/esbuild.yml
README.md is not source code file, so its changes should not trigger the build like `tsc-build`.
> esbuild: ignore *.md

- packages/costa/src/runnable.ts
- packages/daemon/src/runner/job-runner.ts
- packages/daemon/src/utils.ts
- packages/daemon/test/runner/helper.test.ts
- packages/daemon/test/utils/job-runner.test.ts
- yarn.lock
Refer to Issue #569 
Pipeline works as following now:
provide a plugin-specific working dir for data-collect plugin. One data-collect plugin will download and maintain data in this working dir.
provide the same working dir to data-access plugin. Data-access plugin can also modify contents in this working directory.
This mechanism has the following problems that we hope data-collect plugin can make full use of this working directory. For example, they can reuse existing data, do some data cache, and optimize storage space. But since data-access plugin will also modify the same directory, the data-collect plugin will get lost
To solve this problem, I suggest we keep the current style for data-collect. Meanwhile, we provide a temp directory (job-specific) directory for data-access. This can …
> pipeline, daemon: split data dir for data-collect and data-access

- .github/workflows/beta.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ for more details.
It addresses this problem at https://github.com/alibaba/pipcook/pull/655#issuecomment-741675083.
> build: use new syntax to update env in workflow

- packages/boa/binding.gyp
- packages/boa/src/binding.cc
- packages/boa/tools/install-python.js
- packages/boa/tools/utils.js
This PR tries to remove the specific version from the source code and gyp config, to switch the python version, change the function `getPythonVersion()` in tools/utils.js.
And I also add a TODO which is able to automatically detect the python library name from the corresponding conda source, which will be done in the next PR.
> boa: enable python version switch in manual way

- .gitignore
- packages/cli/src/bin/pipcook-daemon.ts
This PR checks for the BOOTSTRAP_HOME and prints a readable log instead of the stack trace.
> cli: check if BOOTSTRAP_HOME exists before starts

- .github/workflows/build.yml
- docs/contributing/contribute-a-plugin.md
- docs/zh-cn/contributing/contribute-a-plugin.md
- packages/cli/src/actions/dev-plugin.ts
- packages/cli/src/bin/pipcook-plugin.ts
- packages/cli/src/service/plugin.ts
See https://github.com/imgcook/create-pipcook-plugin. This PR adds a new command to use create-pipcook-plugin to improve the UX for plugin developers:
```sh
$ pipcook plugin create foobar --category data-collect
```
This deprecated the old `dev-plugin` command which will be removed at 2.0 :)
> cli: add new command to use create-pipcook-plugin

- notebooks/pipcook_image_classification.ipynb
- notebooks/pipcook_object_detection.ipynb
As we have upgraded to the v1.3.0, it validates the Node.js version to be bigger than 10.19.
> notebook: upgrade the nodejs version to 12.19

- packages/boa/binding.gyp
- packages/boa/lib/worker.js
- packages/boa/package.json
- packages/boa/src/core/object.cc
- packages/boa/src/core/object.h
- packages/boa/tests/base/async.js
- packages/boa/tools/check-dependence.js
Node.js 12 requires a higher GLIBC, which won't be supported on some platforms, thus this PR downgrades the Node.js and NAPI requirements. Now the boa is able to work with Node.js 10.13 and NAPI3.
> build: make boa work with Node10 and NAPI3

- .github/workflows/esbuild.yml
There is a difference between esbuild and TSC in module import:
origin code:
```js
import * as fs from 'fs';
```
tsc:
```js
const fs = require('fs');
```
esbuild:
```js
const fs = __toModule(require('fs'));
```
This makes the `sinon.stub` invalid. So we disable the test for esbuild, we will enable it again if esbuild supports to disable `esModuleInterop`.
> esbuild: disable test for esbuild

- packages/daemon/src/utils.ts
- packages/daemon/test/runner/helper.test.ts
Fix: `fs.copyFile(src, dest, fs.constants.COPYFILE_FICLONE)`  blocks the promise train, because `grancful-fs` which is depended by `fs-extra` misses the callback function. see:
https://github.com/isaacs/node-graceful-fs/pull/202
> fix copyFile block with option COPYFILE_FICLONE

- packages/cli/src/utils/script.test.ts
- packages/cli/src/utils/script.ts
We should use `url.pathname` to get the real path so that support the query string.
> cli: fix file protocol uri with query

- packages/cli/src/bin/pipcook.ts
We should add the command `install` when it's ready.
Should fix issue #745 .
> cli: hidden command `install` and add logs for command `clean`

- packages/cli/src/bin/pipcook.ts
- packages/cli/tools/setup.sh
Read from `package.json` at the root directory to make true we can get the correct version string.
> cli: fix cli version error

- packages/costa/src/index.test.ts
- packages/costa/src/index.ts
Support all the entries exporting from one script. The script could export entries like:
```js
export = {
datasource: datasourceEntry,
dataflow: dataflowEntry,
model: modelEntry
}
```
> costa: support all entries in one script

- packages/cli/src/utils/script.test.ts
- packages/cli/src/utils/script.ts
- packages/costa/src/index.ts
We could debug the scripts if the script files are not copied.
> cli: import script without copy if the script protocol is `file:`

- packages/cli/src/utils/script.test.ts
- packages/cli/src/utils/script.ts
As the [RFC-1808](https://tools.ietf.org/html/rfc1808#section-2.2), we could support the relative path for script uri like:
```json
{
"datasource": "file:relative/path/to/script.js"
}
```
The real path is resolved as `${process.cwd()}/relative/path/to/script.js`.
> cli: support relative path for script uri

- packages/cli/package.json
- packages/cli/src/utils/index.ts
- packages/costa/package.json
The module `request` has been deprecated, see https://github.com/request/request/issues/3142, use `bent` instead of it.
> meta: use bent instead of request

- packages/cli/src/utils/cache.test.ts
- packages/cli/src/utils/cache.ts
The next time you run pipline, an error will be thrown when you exit the program while downloading
> cli: fix fetch with cache

- .github/workflows/build.yml
The cache for `boa` is unused and should be removed.
> ci: remove cache for boa
